<!--
Это инструмент, любезно созданный и выложенный в OpenSource компанией AOL.

<ul>
<li><a href="http://www.artzstudio.com/2008/07/optimizing-web-performance-with-aol-pagetest/">Video tutorial by David Artz on using Pagetest</a></li>
<li><a href="http://www.ryandoherty.net/2008/10/12/optimizing-openspacebook/">Walkthrough by Ryan Doherty examining the impact of optimization on performance</a></li>
<li><a href="http://www.webpagetest.org/">Public WebPagetest site with testing from Dulles VA and New Zealand</a></li>
</ul>
-->

Welcome. Pagetest allows you to provide the URL of a webpage to be tested.
The test will be conducted from the location specified and you will be provided a waterfall of your page load performance
as well as a comparison against an optimization checklist. Please
visit the <a href="http://pagetest.wiki.sourceforge.net/">PageTest wiki page</a> for more information.
<br><br>
Here are some useful resources that will help you gett the most out of Pagetest:
<br>
<ul>
<li><a href="http://www.artzstudio.com/2008/07/optimizing-web-performance-with-aol-pagetest/">Video tutorial by David Artz on using Pagetest</a></li>
<li><a href="http://www.ryandoherty.net/2008/10/12/optimizing-openspacebook/">Walkthrough by Ryan Doherty examining the impact of optimization on performance</a></li>
<li><a href="http://www.webpagetest.org/">Public WebPagetest site with testing from Dulles VA and New Zealand</a></li>
</ul>

